/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module cby_2__1_(chany_bottom_in, chany_top_in, ccff_head, chany_bottom_out, chany_top_out, right_grid_pin_0_, left_grid_pin_16_, left_grid_pin_17_, left_grid_pin_18_, left_grid_pin_19_, left_grid_pin_20_, left_grid_pin_21_, left_grid_pin_22_, left_grid_pin_23_, left_grid_pin_24_, left_grid_pin_25_, left_grid_pin_26_, left_grid_pin_27_, left_grid_pin_28_, left_grid_pin_29_, left_grid_pin_30_, left_grid_pin_31_, ccff_tail, IO_ISOL_N, gfpga_pad_EMBEDDED_IO_HD_SOC_IN, gfpga_pad_EMBEDDED_IO_HD_SOC_OUT, gfpga_pad_EMBEDDED_IO_HD_SOC_DIR, left_width_0_height_0__pin_0_, left_width_0_height_0__pin_1_upper, left_width_0_height_0__pin_1_lower, prog_clk_0_W_in, prog_clk_0_S_out, prog_clk_0_N_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input IO_ISOL_N;
  input ccff_head;
  output ccff_tail;
  input [0:19] chany_bottom_in;
  output [0:19] chany_bottom_out;
  input [0:19] chany_top_in;
  output [0:19] chany_top_out;
  output gfpga_pad_EMBEDDED_IO_HD_SOC_DIR;
  input gfpga_pad_EMBEDDED_IO_HD_SOC_IN;
  output gfpga_pad_EMBEDDED_IO_HD_SOC_OUT;
  output left_grid_pin_16_;
  output left_grid_pin_17_;
  output left_grid_pin_18_;
  output left_grid_pin_19_;
  output left_grid_pin_20_;
  output left_grid_pin_21_;
  output left_grid_pin_22_;
  output left_grid_pin_23_;
  output left_grid_pin_24_;
  output left_grid_pin_25_;
  output left_grid_pin_26_;
  output left_grid_pin_27_;
  output left_grid_pin_28_;
  output left_grid_pin_29_;
  output left_grid_pin_30_;
  output left_grid_pin_31_;
  input left_width_0_height_0__pin_0_;
  output left_width_0_height_0__pin_1_lower;
  output left_width_0_height_0__pin_1_upper;
  wire \logical_tile_io_mode_io__0.ccff_head ;
  wire \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.SOC_DIR_N ;
  wire \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ;
  wire \mem_left_ipin_0.ccff_tail ;
  wire \mem_left_ipin_0.mem_out[0] ;
  wire \mem_left_ipin_0.mem_out[1] ;
  wire \mem_left_ipin_0.mem_out[2] ;
  wire \mem_right_ipin_0.ccff_tail ;
  wire \mem_right_ipin_0.mem_out[0] ;
  wire \mem_right_ipin_0.mem_out[1] ;
  wire \mem_right_ipin_0.mem_out[2] ;
  wire \mem_right_ipin_1.ccff_tail ;
  wire \mem_right_ipin_1.mem_out[0] ;
  wire \mem_right_ipin_1.mem_out[1] ;
  wire \mem_right_ipin_1.mem_out[2] ;
  wire \mem_right_ipin_10.ccff_head ;
  wire \mem_right_ipin_10.ccff_tail ;
  wire \mem_right_ipin_10.mem_out[0] ;
  wire \mem_right_ipin_10.mem_out[1] ;
  wire \mem_right_ipin_10.mem_out[2] ;
  wire \mem_right_ipin_11.ccff_tail ;
  wire \mem_right_ipin_11.mem_out[0] ;
  wire \mem_right_ipin_11.mem_out[1] ;
  wire \mem_right_ipin_11.mem_out[2] ;
  wire \mem_right_ipin_12.ccff_tail ;
  wire \mem_right_ipin_12.mem_out[0] ;
  wire \mem_right_ipin_12.mem_out[1] ;
  wire \mem_right_ipin_12.mem_out[2] ;
  wire \mem_right_ipin_13.ccff_tail ;
  wire \mem_right_ipin_13.mem_out[0] ;
  wire \mem_right_ipin_13.mem_out[1] ;
  wire \mem_right_ipin_13.mem_out[2] ;
  wire \mem_right_ipin_14.ccff_tail ;
  wire \mem_right_ipin_14.mem_out[0] ;
  wire \mem_right_ipin_14.mem_out[1] ;
  wire \mem_right_ipin_14.mem_out[2] ;
  wire \mem_right_ipin_15.mem_out[0] ;
  wire \mem_right_ipin_15.mem_out[1] ;
  wire \mem_right_ipin_15.mem_out[2] ;
  wire \mem_right_ipin_2.ccff_tail ;
  wire \mem_right_ipin_2.mem_out[0] ;
  wire \mem_right_ipin_2.mem_out[1] ;
  wire \mem_right_ipin_2.mem_out[2] ;
  wire \mem_right_ipin_3.ccff_tail ;
  wire \mem_right_ipin_3.mem_out[0] ;
  wire \mem_right_ipin_3.mem_out[1] ;
  wire \mem_right_ipin_3.mem_out[2] ;
  wire \mem_right_ipin_4.ccff_tail ;
  wire \mem_right_ipin_4.mem_out[0] ;
  wire \mem_right_ipin_4.mem_out[1] ;
  wire \mem_right_ipin_4.mem_out[2] ;
  wire \mem_right_ipin_5.ccff_tail ;
  wire \mem_right_ipin_5.mem_out[0] ;
  wire \mem_right_ipin_5.mem_out[1] ;
  wire \mem_right_ipin_5.mem_out[2] ;
  wire \mem_right_ipin_6.ccff_tail ;
  wire \mem_right_ipin_6.mem_out[0] ;
  wire \mem_right_ipin_6.mem_out[1] ;
  wire \mem_right_ipin_6.mem_out[2] ;
  wire \mem_right_ipin_7.ccff_tail ;
  wire \mem_right_ipin_7.mem_out[0] ;
  wire \mem_right_ipin_7.mem_out[1] ;
  wire \mem_right_ipin_7.mem_out[2] ;
  wire \mem_right_ipin_8.ccff_tail ;
  wire \mem_right_ipin_8.mem_out[0] ;
  wire \mem_right_ipin_8.mem_out[1] ;
  wire \mem_right_ipin_8.mem_out[2] ;
  wire \mem_right_ipin_9.mem_out[0] ;
  wire \mem_right_ipin_9.mem_out[1] ;
  wire \mem_right_ipin_9.mem_out[2] ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_7_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_8_X ;
  wire \mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_9_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_0_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_1_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_2_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_3_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_4_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_5_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_6_X ;
  wire \mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_7_X ;
  output prog_clk_0_N_out;
  output prog_clk_0_S_out;
  input prog_clk_0_W_in;
  output right_grid_pin_0_;
  sky130_fd_sc_hd__conb_1 _17_ (
    .HI(_16_)
  );
  sky130_fd_sc_hd__conb_1 _18_ (
    .HI(_00_)
  );
  sky130_fd_sc_hd__conb_1 _19_ (
    .HI(_01_)
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .HI(_02_)
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .HI(_03_)
  );
  sky130_fd_sc_hd__conb_1 _22_ (
    .HI(_04_)
  );
  sky130_fd_sc_hd__conb_1 _23_ (
    .HI(_05_)
  );
  sky130_fd_sc_hd__conb_1 _24_ (
    .HI(_06_)
  );
  sky130_fd_sc_hd__conb_1 _25_ (
    .HI(_07_)
  );
  sky130_fd_sc_hd__conb_1 _26_ (
    .HI(_08_)
  );
  sky130_fd_sc_hd__conb_1 _27_ (
    .HI(_09_)
  );
  sky130_fd_sc_hd__conb_1 _28_ (
    .HI(_10_)
  );
  sky130_fd_sc_hd__conb_1 _29_ (
    .HI(_11_)
  );
  sky130_fd_sc_hd__conb_1 _30_ (
    .HI(_12_)
  );
  sky130_fd_sc_hd__conb_1 _31_ (
    .HI(_13_)
  );
  sky130_fd_sc_hd__conb_1 _32_ (
    .HI(_14_)
  );
  sky130_fd_sc_hd__conb_1 _33_ (
    .HI(_15_)
  );
  sky130_fd_sc_hd__buf_2 _34_ (
    .A(chany_top_in[19]),
    .X(chany_bottom_out[19])
  );
  sky130_fd_sc_hd__buf_2 _35_ (
    .A(chany_top_in[18]),
    .X(chany_bottom_out[18])
  );
  sky130_fd_sc_hd__buf_2 _36_ (
    .A(chany_top_in[17]),
    .X(chany_bottom_out[17])
  );
  sky130_fd_sc_hd__buf_2 _37_ (
    .A(chany_top_in[16]),
    .X(chany_bottom_out[16])
  );
  sky130_fd_sc_hd__buf_2 _38_ (
    .A(chany_top_in[15]),
    .X(chany_bottom_out[15])
  );
  sky130_fd_sc_hd__buf_2 _39_ (
    .A(chany_top_in[14]),
    .X(chany_bottom_out[14])
  );
  sky130_fd_sc_hd__buf_2 _40_ (
    .A(chany_top_in[13]),
    .X(chany_bottom_out[13])
  );
  sky130_fd_sc_hd__buf_2 _41_ (
    .A(chany_top_in[12]),
    .X(chany_bottom_out[12])
  );
  sky130_fd_sc_hd__buf_2 _42_ (
    .A(chany_top_in[11]),
    .X(chany_bottom_out[11])
  );
  sky130_fd_sc_hd__buf_2 _43_ (
    .A(chany_top_in[10]),
    .X(chany_bottom_out[10])
  );
  sky130_fd_sc_hd__buf_2 _44_ (
    .A(chany_top_in[9]),
    .X(chany_bottom_out[9])
  );
  sky130_fd_sc_hd__buf_2 _45_ (
    .A(chany_top_in[8]),
    .X(chany_bottom_out[8])
  );
  sky130_fd_sc_hd__buf_2 _46_ (
    .A(chany_top_in[7]),
    .X(chany_bottom_out[7])
  );
  sky130_fd_sc_hd__buf_2 _47_ (
    .A(chany_top_in[6]),
    .X(chany_bottom_out[6])
  );
  sky130_fd_sc_hd__buf_2 _48_ (
    .A(chany_top_in[5]),
    .X(chany_bottom_out[5])
  );
  sky130_fd_sc_hd__buf_2 _49_ (
    .A(chany_top_in[4]),
    .X(chany_bottom_out[4])
  );
  sky130_fd_sc_hd__buf_2 _50_ (
    .A(chany_top_in[3]),
    .X(chany_bottom_out[3])
  );
  sky130_fd_sc_hd__buf_2 _51_ (
    .A(chany_top_in[2]),
    .X(chany_bottom_out[2])
  );
  sky130_fd_sc_hd__buf_2 _52_ (
    .A(chany_top_in[1]),
    .X(chany_bottom_out[1])
  );
  sky130_fd_sc_hd__buf_2 _53_ (
    .A(chany_top_in[0]),
    .X(chany_bottom_out[0])
  );
  sky130_fd_sc_hd__buf_2 _54_ (
    .A(chany_bottom_in[19]),
    .X(chany_top_out[19])
  );
  sky130_fd_sc_hd__buf_2 _55_ (
    .A(chany_bottom_in[18]),
    .X(chany_top_out[18])
  );
  sky130_fd_sc_hd__buf_2 _56_ (
    .A(chany_bottom_in[17]),
    .X(chany_top_out[17])
  );
  sky130_fd_sc_hd__buf_2 _57_ (
    .A(chany_bottom_in[16]),
    .X(chany_top_out[16])
  );
  sky130_fd_sc_hd__buf_2 _58_ (
    .A(chany_bottom_in[15]),
    .X(chany_top_out[15])
  );
  sky130_fd_sc_hd__buf_2 _59_ (
    .A(chany_bottom_in[14]),
    .X(chany_top_out[14])
  );
  sky130_fd_sc_hd__buf_2 _60_ (
    .A(chany_bottom_in[13]),
    .X(chany_top_out[13])
  );
  sky130_fd_sc_hd__buf_2 _61_ (
    .A(chany_bottom_in[12]),
    .X(chany_top_out[12])
  );
  sky130_fd_sc_hd__buf_2 _62_ (
    .A(chany_bottom_in[11]),
    .X(chany_top_out[11])
  );
  sky130_fd_sc_hd__buf_2 _63_ (
    .A(chany_bottom_in[10]),
    .X(chany_top_out[10])
  );
  sky130_fd_sc_hd__buf_2 _64_ (
    .A(chany_bottom_in[9]),
    .X(chany_top_out[9])
  );
  sky130_fd_sc_hd__buf_2 _65_ (
    .A(chany_bottom_in[8]),
    .X(chany_top_out[8])
  );
  sky130_fd_sc_hd__buf_2 _66_ (
    .A(chany_bottom_in[7]),
    .X(chany_top_out[7])
  );
  sky130_fd_sc_hd__buf_2 _67_ (
    .A(chany_bottom_in[6]),
    .X(chany_top_out[6])
  );
  sky130_fd_sc_hd__buf_2 _68_ (
    .A(chany_bottom_in[5]),
    .X(chany_top_out[5])
  );
  sky130_fd_sc_hd__buf_2 _69_ (
    .A(chany_bottom_in[4]),
    .X(chany_top_out[4])
  );
  sky130_fd_sc_hd__buf_2 _70_ (
    .A(chany_bottom_in[3]),
    .X(chany_top_out[3])
  );
  sky130_fd_sc_hd__buf_2 _71_ (
    .A(chany_bottom_in[2]),
    .X(chany_top_out[2])
  );
  sky130_fd_sc_hd__buf_2 _72_ (
    .A(chany_bottom_in[1]),
    .X(chany_top_out[1])
  );
  sky130_fd_sc_hd__buf_2 _73_ (
    .A(chany_bottom_in[0]),
    .X(chany_top_out[0])
  );
  sky130_fd_sc_hd__buf_2 _74_ (
    .A(left_width_0_height_0__pin_1_lower),
    .X(left_width_0_height_0__pin_1_upper)
  );
  sky130_fd_sc_hd__inv_1 \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.INV_SOC_DIR  (
    .A(gfpga_pad_EMBEDDED_IO_HD_SOC_DIR),
    .Y(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.SOC_DIR_N )
  );
  sky130_fd_sc_hd__ebufn_4 \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.IN_PROTECT_GATE  (
    .A(gfpga_pad_EMBEDDED_IO_HD_SOC_IN),
    .TE_B(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.SOC_DIR_N ),
    .Z(left_width_0_height_0__pin_1_lower)
  );
  sky130_fd_sc_hd__or2b_4 \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.ISOL_EN_GATE  (
    .A(ccff_tail),
    .B_N(IO_ISOL_N),
    .X(gfpga_pad_EMBEDDED_IO_HD_SOC_DIR)
  );
  sky130_fd_sc_hd__ebufn_4 \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_0_.OUT_PROTECT_GATE  (
    .A(left_width_0_height_0__pin_0_),
    .TE_B(gfpga_pad_EMBEDDED_IO_HD_SOC_DIR),
    .Z(gfpga_pad_EMBEDDED_IO_HD_SOC_OUT)
  );
  sky130_fd_sc_hd__dfxtp_1 \logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\logical_tile_io_mode_io__0.ccff_head ),
    .Q(ccff_tail)
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_left_ipin_0.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(ccff_head),
    .Q(\mem_left_ipin_0.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_left_ipin_0.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_left_ipin_0.mem_out[0] ),
    .Q(\mem_left_ipin_0.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_left_ipin_0.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_left_ipin_0.mem_out[1] ),
    .Q(\mem_left_ipin_0.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_left_ipin_0.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_left_ipin_0.mem_out[2] ),
    .Q(\mem_left_ipin_0.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_0.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_left_ipin_0.ccff_tail ),
    .Q(\mem_right_ipin_0.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_0.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_0.mem_out[0] ),
    .Q(\mem_right_ipin_0.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_0.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_0.mem_out[1] ),
    .Q(\mem_right_ipin_0.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_0.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_0.mem_out[2] ),
    .Q(\mem_right_ipin_0.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_1.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_0.ccff_tail ),
    .Q(\mem_right_ipin_1.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_1.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_1.mem_out[0] ),
    .Q(\mem_right_ipin_1.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_1.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_1.mem_out[1] ),
    .Q(\mem_right_ipin_1.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_1.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_1.mem_out[2] ),
    .Q(\mem_right_ipin_1.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_10.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_10.ccff_head ),
    .Q(\mem_right_ipin_10.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_10.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_10.mem_out[0] ),
    .Q(\mem_right_ipin_10.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_10.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_10.mem_out[1] ),
    .Q(\mem_right_ipin_10.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_10.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_10.mem_out[2] ),
    .Q(\mem_right_ipin_10.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_11.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_10.ccff_tail ),
    .Q(\mem_right_ipin_11.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_11.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_11.mem_out[0] ),
    .Q(\mem_right_ipin_11.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_11.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_11.mem_out[1] ),
    .Q(\mem_right_ipin_11.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_11.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_11.mem_out[2] ),
    .Q(\mem_right_ipin_11.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_12.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_11.ccff_tail ),
    .Q(\mem_right_ipin_12.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_12.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_12.mem_out[0] ),
    .Q(\mem_right_ipin_12.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_12.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_12.mem_out[1] ),
    .Q(\mem_right_ipin_12.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_12.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_12.mem_out[2] ),
    .Q(\mem_right_ipin_12.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_13.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_12.ccff_tail ),
    .Q(\mem_right_ipin_13.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_13.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_13.mem_out[0] ),
    .Q(\mem_right_ipin_13.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_13.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_13.mem_out[1] ),
    .Q(\mem_right_ipin_13.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_13.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_13.mem_out[2] ),
    .Q(\mem_right_ipin_13.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_14.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_13.ccff_tail ),
    .Q(\mem_right_ipin_14.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_14.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_14.mem_out[0] ),
    .Q(\mem_right_ipin_14.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_14.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_14.mem_out[1] ),
    .Q(\mem_right_ipin_14.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_14.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_14.mem_out[2] ),
    .Q(\mem_right_ipin_14.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_15.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_14.ccff_tail ),
    .Q(\mem_right_ipin_15.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_15.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_15.mem_out[0] ),
    .Q(\mem_right_ipin_15.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_15.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_15.mem_out[1] ),
    .Q(\mem_right_ipin_15.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_15.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_15.mem_out[2] ),
    .Q(\logical_tile_io_mode_io__0.ccff_head )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_2.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_1.ccff_tail ),
    .Q(\mem_right_ipin_2.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_2.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_2.mem_out[0] ),
    .Q(\mem_right_ipin_2.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_2.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_2.mem_out[1] ),
    .Q(\mem_right_ipin_2.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_2.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_2.mem_out[2] ),
    .Q(\mem_right_ipin_2.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_3.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_2.ccff_tail ),
    .Q(\mem_right_ipin_3.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_3.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_3.mem_out[0] ),
    .Q(\mem_right_ipin_3.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_3.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_3.mem_out[1] ),
    .Q(\mem_right_ipin_3.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_3.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_3.mem_out[2] ),
    .Q(\mem_right_ipin_3.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_4.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_3.ccff_tail ),
    .Q(\mem_right_ipin_4.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_4.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_4.mem_out[0] ),
    .Q(\mem_right_ipin_4.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_4.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_4.mem_out[1] ),
    .Q(\mem_right_ipin_4.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_4.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_4.mem_out[2] ),
    .Q(\mem_right_ipin_4.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_5.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_4.ccff_tail ),
    .Q(\mem_right_ipin_5.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_5.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_5.mem_out[0] ),
    .Q(\mem_right_ipin_5.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_5.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_5.mem_out[1] ),
    .Q(\mem_right_ipin_5.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_5.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_5.mem_out[2] ),
    .Q(\mem_right_ipin_5.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_6.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_5.ccff_tail ),
    .Q(\mem_right_ipin_6.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_6.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_6.mem_out[0] ),
    .Q(\mem_right_ipin_6.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_6.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_6.mem_out[1] ),
    .Q(\mem_right_ipin_6.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_6.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_6.mem_out[2] ),
    .Q(\mem_right_ipin_6.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_7.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_6.ccff_tail ),
    .Q(\mem_right_ipin_7.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_7.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_7.mem_out[0] ),
    .Q(\mem_right_ipin_7.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_7.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_7.mem_out[1] ),
    .Q(\mem_right_ipin_7.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_7.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_7.mem_out[2] ),
    .Q(\mem_right_ipin_7.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_8.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_7.ccff_tail ),
    .Q(\mem_right_ipin_8.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_8.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_8.mem_out[0] ),
    .Q(\mem_right_ipin_8.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_8.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_8.mem_out[1] ),
    .Q(\mem_right_ipin_8.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_8.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_8.mem_out[2] ),
    .Q(\mem_right_ipin_8.ccff_tail )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_9.sky130_fd_sc_hd__dfxtp_1_0_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_8.ccff_tail ),
    .Q(\mem_right_ipin_9.mem_out[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_9.sky130_fd_sc_hd__dfxtp_1_1_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_9.mem_out[0] ),
    .Q(\mem_right_ipin_9.mem_out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_9.sky130_fd_sc_hd__dfxtp_1_2_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_9.mem_out[1] ),
    .Q(\mem_right_ipin_9.mem_out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 \mem_right_ipin_9.sky130_fd_sc_hd__dfxtp_1_3_  (
    .CLK(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk ),
    .D(\mem_right_ipin_9.mem_out[2] ),
    .Q(\mem_right_ipin_10.ccff_head )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_left_ipin_0.mem_out[0] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l1_in_1_  (
    .A0(chany_top_in[2]),
    .A1(chany_bottom_in[2]),
    .S(\mem_left_ipin_0.mem_out[0] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l1_in_2_  (
    .A0(chany_top_in[4]),
    .A1(chany_bottom_in[4]),
    .S(\mem_left_ipin_0.mem_out[0] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l2_in_0_  (
    .A0(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_left_ipin_0.mem_out[1] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l2_in_1_  (
    .A0(chany_bottom_in[10]),
    .A1(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_left_ipin_0.mem_out[1] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l2_in_2_  (
    .A0(chany_bottom_in[16]),
    .A1(chany_top_in[10]),
    .S(\mem_left_ipin_0.mem_out[1] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l2_in_3_  (
    .A0(_04_),
    .A1(chany_top_in[16]),
    .S(\mem_left_ipin_0.mem_out[1] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l3_in_0_  (
    .A0(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_left_ipin_0.mem_out[2] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l3_in_1_  (
    .A0(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_left_ipin_0.mem_out[2] ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_left_ipin_0.mux_l4_in_0_  (
    .A0(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_left_ipin_0.ccff_tail ),
    .X(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_left_ipin_0.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_left_ipin_0.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(right_grid_pin_0_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_0.mem_out[0] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l1_in_1_  (
    .A0(chany_top_in[3]),
    .A1(chany_bottom_in[3]),
    .S(\mem_right_ipin_0.mem_out[0] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l1_in_2_  (
    .A0(chany_top_in[5]),
    .A1(chany_bottom_in[5]),
    .S(\mem_right_ipin_0.mem_out[0] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l2_in_0_  (
    .A0(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_0.mem_out[1] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l2_in_1_  (
    .A0(chany_bottom_in[11]),
    .A1(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_0.mem_out[1] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l2_in_2_  (
    .A0(chany_bottom_in[17]),
    .A1(chany_top_in[11]),
    .S(\mem_right_ipin_0.mem_out[1] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l2_in_3_  (
    .A0(_05_),
    .A1(chany_top_in[17]),
    .S(\mem_right_ipin_0.mem_out[1] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l3_in_0_  (
    .A0(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_0.mem_out[2] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l3_in_1_  (
    .A0(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_0.mem_out[2] ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_0.mux_l4_in_0_  (
    .A0(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_0.ccff_tail ),
    .X(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_0.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_0.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_16_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_1.mem_out[0] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l2_in_0_  (
    .A0(chany_bottom_in[2]),
    .A1(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_1.mem_out[1] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l2_in_1_  (
    .A0(chany_bottom_in[6]),
    .A1(chany_top_in[2]),
    .S(\mem_right_ipin_1.mem_out[1] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l2_in_2_  (
    .A0(chany_bottom_in[14]),
    .A1(chany_top_in[6]),
    .S(\mem_right_ipin_1.mem_out[1] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l2_in_3_  (
    .A0(_06_),
    .A1(chany_top_in[14]),
    .S(\mem_right_ipin_1.mem_out[1] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l3_in_0_  (
    .A0(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_1.mem_out[2] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l3_in_1_  (
    .A0(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_1.mem_out[2] ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_1.mux_l4_in_0_  (
    .A0(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_1.ccff_tail ),
    .X(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_1.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_1.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_17_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_10.mem_out[0] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l2_in_0_  (
    .A0(chany_bottom_in[3]),
    .A1(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_10.mem_out[1] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l2_in_1_  (
    .A0(chany_bottom_in[7]),
    .A1(chany_top_in[3]),
    .S(\mem_right_ipin_10.mem_out[1] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l2_in_2_  (
    .A0(chany_bottom_in[15]),
    .A1(chany_top_in[7]),
    .S(\mem_right_ipin_10.mem_out[1] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l2_in_3_  (
    .A0(_07_),
    .A1(chany_top_in[15]),
    .S(\mem_right_ipin_10.mem_out[1] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l3_in_0_  (
    .A0(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_10.mem_out[2] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l3_in_1_  (
    .A0(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_10.mem_out[2] ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_10.mux_l4_in_0_  (
    .A0(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_10.ccff_tail ),
    .X(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_10.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_10.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_26_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_11.mem_out[0] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l1_in_1_  (
    .A0(chany_top_in[2]),
    .A1(chany_bottom_in[2]),
    .S(\mem_right_ipin_11.mem_out[0] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l1_in_2_  (
    .A0(chany_top_in[6]),
    .A1(chany_bottom_in[6]),
    .S(\mem_right_ipin_11.mem_out[0] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l2_in_0_  (
    .A0(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_11.mem_out[1] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l2_in_1_  (
    .A0(chany_bottom_in[12]),
    .A1(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_11.mem_out[1] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l2_in_2_  (
    .A0(chany_bottom_in[16]),
    .A1(chany_top_in[12]),
    .S(\mem_right_ipin_11.mem_out[1] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l2_in_3_  (
    .A0(_08_),
    .A1(chany_top_in[16]),
    .S(\mem_right_ipin_11.mem_out[1] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l3_in_0_  (
    .A0(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_11.mem_out[2] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l3_in_1_  (
    .A0(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_11.mem_out[2] ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_11.mux_l4_in_0_  (
    .A0(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_11.ccff_tail ),
    .X(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_11.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_11.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_27_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_12.mem_out[0] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l1_in_1_  (
    .A0(chany_top_in[3]),
    .A1(chany_bottom_in[3]),
    .S(\mem_right_ipin_12.mem_out[0] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l1_in_2_  (
    .A0(chany_top_in[7]),
    .A1(chany_bottom_in[7]),
    .S(\mem_right_ipin_12.mem_out[0] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l2_in_0_  (
    .A0(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_12.mem_out[1] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l2_in_1_  (
    .A0(chany_bottom_in[13]),
    .A1(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_12.mem_out[1] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l2_in_2_  (
    .A0(chany_bottom_in[17]),
    .A1(chany_top_in[13]),
    .S(\mem_right_ipin_12.mem_out[1] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l2_in_3_  (
    .A0(_09_),
    .A1(chany_top_in[17]),
    .S(\mem_right_ipin_12.mem_out[1] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l3_in_0_  (
    .A0(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_12.mem_out[2] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l3_in_1_  (
    .A0(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_12.mem_out[2] ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_12.mux_l4_in_0_  (
    .A0(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_12.ccff_tail ),
    .X(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_12.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_12.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_28_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_13.mem_out[0] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l2_in_0_  (
    .A0(chany_bottom_in[2]),
    .A1(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_13.mem_out[1] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l2_in_1_  (
    .A0(chany_bottom_in[10]),
    .A1(chany_top_in[2]),
    .S(\mem_right_ipin_13.mem_out[1] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l2_in_2_  (
    .A0(chany_bottom_in[18]),
    .A1(chany_top_in[10]),
    .S(\mem_right_ipin_13.mem_out[1] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l2_in_3_  (
    .A0(_10_),
    .A1(chany_top_in[18]),
    .S(\mem_right_ipin_13.mem_out[1] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l3_in_0_  (
    .A0(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_13.mem_out[2] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l3_in_1_  (
    .A0(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_13.mem_out[2] ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_13.mux_l4_in_0_  (
    .A0(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_13.ccff_tail ),
    .X(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_13.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_13.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_29_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_14.mem_out[0] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l2_in_0_  (
    .A0(chany_bottom_in[3]),
    .A1(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_14.mem_out[1] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l2_in_1_  (
    .A0(chany_bottom_in[11]),
    .A1(chany_top_in[3]),
    .S(\mem_right_ipin_14.mem_out[1] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l2_in_2_  (
    .A0(chany_bottom_in[19]),
    .A1(chany_top_in[11]),
    .S(\mem_right_ipin_14.mem_out[1] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l2_in_3_  (
    .A0(_11_),
    .A1(chany_top_in[19]),
    .S(\mem_right_ipin_14.mem_out[1] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l3_in_0_  (
    .A0(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_14.mem_out[2] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l3_in_1_  (
    .A0(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_14.mem_out[2] ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_14.mux_l4_in_0_  (
    .A0(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_14.ccff_tail ),
    .X(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_14.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_14.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_30_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_15.mem_out[0] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l1_in_1_  (
    .A0(chany_top_in[2]),
    .A1(chany_bottom_in[2]),
    .S(\mem_right_ipin_15.mem_out[0] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l1_in_2_  (
    .A0(chany_top_in[4]),
    .A1(chany_bottom_in[4]),
    .S(\mem_right_ipin_15.mem_out[0] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l2_in_0_  (
    .A0(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_15.mem_out[1] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l2_in_1_  (
    .A0(chany_bottom_in[10]),
    .A1(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_15.mem_out[1] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l2_in_2_  (
    .A0(chany_bottom_in[16]),
    .A1(chany_top_in[10]),
    .S(\mem_right_ipin_15.mem_out[1] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l2_in_3_  (
    .A0(_12_),
    .A1(chany_top_in[16]),
    .S(\mem_right_ipin_15.mem_out[1] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l3_in_0_  (
    .A0(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_15.mem_out[2] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l3_in_1_  (
    .A0(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_15.mem_out[2] ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_15.mux_l4_in_0_  (
    .A0(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\logical_tile_io_mode_io__0.ccff_head ),
    .X(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_15.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_15.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_31_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_2.mem_out[0] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l2_in_0_  (
    .A0(chany_bottom_in[3]),
    .A1(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_2.mem_out[1] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l2_in_1_  (
    .A0(chany_bottom_in[7]),
    .A1(chany_top_in[3]),
    .S(\mem_right_ipin_2.mem_out[1] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l2_in_2_  (
    .A0(chany_bottom_in[15]),
    .A1(chany_top_in[7]),
    .S(\mem_right_ipin_2.mem_out[1] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l2_in_3_  (
    .A0(_13_),
    .A1(chany_top_in[15]),
    .S(\mem_right_ipin_2.mem_out[1] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l3_in_0_  (
    .A0(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_2.mem_out[2] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l3_in_1_  (
    .A0(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_2.mem_out[2] ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_2.mux_l4_in_0_  (
    .A0(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_2.ccff_tail ),
    .X(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_2.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_2.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_18_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_3.mem_out[0] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l1_in_1_  (
    .A0(chany_top_in[2]),
    .A1(chany_bottom_in[2]),
    .S(\mem_right_ipin_3.mem_out[0] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l1_in_2_  (
    .A0(chany_top_in[4]),
    .A1(chany_bottom_in[4]),
    .S(\mem_right_ipin_3.mem_out[0] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l2_in_0_  (
    .A0(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_3.mem_out[1] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l2_in_1_  (
    .A0(chany_bottom_in[8]),
    .A1(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_3.mem_out[1] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l2_in_2_  (
    .A0(chany_bottom_in[14]),
    .A1(chany_top_in[8]),
    .S(\mem_right_ipin_3.mem_out[1] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l2_in_3_  (
    .A0(_14_),
    .A1(chany_top_in[14]),
    .S(\mem_right_ipin_3.mem_out[1] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l3_in_0_  (
    .A0(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_3.mem_out[2] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l3_in_1_  (
    .A0(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_3.mem_out[2] ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_3.mux_l4_in_0_  (
    .A0(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_3.ccff_tail ),
    .X(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_3.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_3.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_19_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_4.mem_out[0] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l1_in_1_  (
    .A0(chany_top_in[3]),
    .A1(chany_bottom_in[3]),
    .S(\mem_right_ipin_4.mem_out[0] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l1_in_2_  (
    .A0(chany_top_in[5]),
    .A1(chany_bottom_in[5]),
    .S(\mem_right_ipin_4.mem_out[0] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l2_in_0_  (
    .A0(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_4.mem_out[1] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l2_in_1_  (
    .A0(chany_bottom_in[9]),
    .A1(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_4.mem_out[1] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l2_in_2_  (
    .A0(chany_bottom_in[15]),
    .A1(chany_top_in[9]),
    .S(\mem_right_ipin_4.mem_out[1] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l2_in_3_  (
    .A0(_15_),
    .A1(chany_top_in[15]),
    .S(\mem_right_ipin_4.mem_out[1] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l3_in_0_  (
    .A0(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_4.mem_out[2] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l3_in_1_  (
    .A0(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_4.mem_out[2] ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_4.mux_l4_in_0_  (
    .A0(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_4.ccff_tail ),
    .X(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_4.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_4.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_20_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_5.mem_out[0] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l2_in_0_  (
    .A0(chany_bottom_in[2]),
    .A1(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_5.mem_out[1] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l2_in_1_  (
    .A0(chany_bottom_in[10]),
    .A1(chany_top_in[2]),
    .S(\mem_right_ipin_5.mem_out[1] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l2_in_2_  (
    .A0(chany_bottom_in[18]),
    .A1(chany_top_in[10]),
    .S(\mem_right_ipin_5.mem_out[1] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l2_in_3_  (
    .A0(_16_),
    .A1(chany_top_in[18]),
    .S(\mem_right_ipin_5.mem_out[1] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l3_in_0_  (
    .A0(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_5.mem_out[2] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l3_in_1_  (
    .A0(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_5.mem_out[2] ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_5.mux_l4_in_0_  (
    .A0(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_5.ccff_tail ),
    .X(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_5.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_5.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_21_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_6.mem_out[0] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l2_in_0_  (
    .A0(chany_bottom_in[3]),
    .A1(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_6.mem_out[1] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l2_in_1_  (
    .A0(chany_bottom_in[11]),
    .A1(chany_top_in[3]),
    .S(\mem_right_ipin_6.mem_out[1] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l2_in_2_  (
    .A0(chany_bottom_in[19]),
    .A1(chany_top_in[11]),
    .S(\mem_right_ipin_6.mem_out[1] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l2_in_3_  (
    .A0(_00_),
    .A1(chany_top_in[19]),
    .S(\mem_right_ipin_6.mem_out[1] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l3_in_0_  (
    .A0(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_6.mem_out[2] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l3_in_1_  (
    .A0(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_6.mem_out[2] ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_6.mux_l4_in_0_  (
    .A0(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_6.ccff_tail ),
    .X(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_6.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_6.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_22_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_7.mem_out[0] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l1_in_1_  (
    .A0(chany_top_in[2]),
    .A1(chany_bottom_in[2]),
    .S(\mem_right_ipin_7.mem_out[0] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l1_in_2_  (
    .A0(chany_top_in[8]),
    .A1(chany_bottom_in[8]),
    .S(\mem_right_ipin_7.mem_out[0] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l2_in_0_  (
    .A0(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_7.mem_out[1] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l2_in_1_  (
    .A0(chany_bottom_in[12]),
    .A1(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_7.mem_out[1] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l2_in_2_  (
    .A0(chany_bottom_in[18]),
    .A1(chany_top_in[12]),
    .S(\mem_right_ipin_7.mem_out[1] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l2_in_3_  (
    .A0(_01_),
    .A1(chany_top_in[18]),
    .S(\mem_right_ipin_7.mem_out[1] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l3_in_0_  (
    .A0(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_7.mem_out[2] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l3_in_1_  (
    .A0(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_7.mem_out[2] ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_7.mux_l4_in_0_  (
    .A0(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_7.ccff_tail ),
    .X(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_7.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_7.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_23_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l1_in_0_  (
    .A0(chany_top_in[1]),
    .A1(chany_bottom_in[1]),
    .S(\mem_right_ipin_8.mem_out[0] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l1_in_1_  (
    .A0(chany_top_in[3]),
    .A1(chany_bottom_in[3]),
    .S(\mem_right_ipin_8.mem_out[0] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l1_in_2_  (
    .A0(chany_top_in[9]),
    .A1(chany_bottom_in[9]),
    .S(\mem_right_ipin_8.mem_out[0] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l2_in_0_  (
    .A0(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_1_X ),
    .A1(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_8.mem_out[1] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l2_in_1_  (
    .A0(chany_bottom_in[13]),
    .A1(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_2_X ),
    .S(\mem_right_ipin_8.mem_out[1] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l2_in_2_  (
    .A0(chany_bottom_in[19]),
    .A1(chany_top_in[13]),
    .S(\mem_right_ipin_8.mem_out[1] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l2_in_3_  (
    .A0(_02_),
    .A1(chany_top_in[19]),
    .S(\mem_right_ipin_8.mem_out[1] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l3_in_0_  (
    .A0(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_8.mem_out[2] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l3_in_1_  (
    .A0(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_8.mem_out[2] ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_8_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_8.mux_l4_in_0_  (
    .A0(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_8_X ),
    .A1(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_7_X ),
    .S(\mem_right_ipin_8.ccff_tail ),
    .X(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_9_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_8.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_8.sky130_fd_sc_hd__mux2_1_9_X ),
    .X(left_grid_pin_24_)
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l1_in_0_  (
    .A0(chany_top_in[0]),
    .A1(chany_bottom_in[0]),
    .S(\mem_right_ipin_9.mem_out[0] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_0_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l2_in_0_  (
    .A0(chany_bottom_in[2]),
    .A1(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_0_X ),
    .S(\mem_right_ipin_9.mem_out[1] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_1_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l2_in_1_  (
    .A0(chany_bottom_in[6]),
    .A1(chany_top_in[2]),
    .S(\mem_right_ipin_9.mem_out[1] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_2_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l2_in_2_  (
    .A0(chany_bottom_in[14]),
    .A1(chany_top_in[6]),
    .S(\mem_right_ipin_9.mem_out[1] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_3_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l2_in_3_  (
    .A0(_03_),
    .A1(chany_top_in[14]),
    .S(\mem_right_ipin_9.mem_out[1] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_4_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l3_in_0_  (
    .A0(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_2_X ),
    .A1(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_1_X ),
    .S(\mem_right_ipin_9.mem_out[2] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_5_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l3_in_1_  (
    .A0(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_4_X ),
    .A1(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_3_X ),
    .S(\mem_right_ipin_9.mem_out[2] ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_6_X )
  );
  sky130_fd_sc_hd__mux2_1 \mux_right_ipin_9.mux_l4_in_0_  (
    .A0(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_6_X ),
    .A1(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_5_X ),
    .S(\mem_right_ipin_10.ccff_head ),
    .X(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_7_X )
  );
  sky130_fd_sc_hd__buf_4 \mux_right_ipin_9.sky130_fd_sc_hd__buf_4_0_  (
    .A(\mux_right_ipin_9.sky130_fd_sc_hd__mux2_1_7_X ),
    .X(left_grid_pin_25_)
  );
  sky130_fd_sc_hd__buf_8 prog_clk_0_FTB00 (
    .A(prog_clk_0_W_in),
    .X(\logical_tile_io_mode_io__0.ltile_phy_iopad_0.EMBEDDED_IO_HD_sky130_fd_sc_hd__dfxtp_1_mem.prog_clk )
  );
  sky130_fd_sc_hd__buf_4 prog_clk_0_N_FTB01 (
    .A(prog_clk_0_W_in),
    .X(prog_clk_0_N_out)
  );
  sky130_fd_sc_hd__buf_4 prog_clk_0_S_FTB01 (
    .A(prog_clk_0_W_in),
    .X(prog_clk_0_S_out)
  );
endmodule
