/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module tie_array(x);
  output [7:0] x;
  sky130_fd_sc_hd__conb_1 \conb_1[0]  (
    .LO(x[0])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[1]  (
    .LO(x[1])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[2]  (
    .LO(x[2])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[3]  (
    .LO(x[3])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[4]  (
    .LO(x[4])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[5]  (
    .LO(x[5])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[6]  (
    .LO(x[6])
  );
  sky130_fd_sc_hd__conb_1 \conb_1[7]  (
    .LO(x[7])
  );
endmodule
